version: '3.5'

services:

  mysql:
    image: mysql:8.0.36
    container_name: mysql
    restart: always
    env_file:
      - .env
    volumes:
      - main:/var/lib/mysql
      - ./db/:/docker-entrypoint-initdb.d/
    ports:
      - 3305:3306
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 1s
      retries: 5

  control-posts:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: control-posts
    working_dir: /control-posts
    volumes:
      - control-posts-node-modules:/control-posts/node_modules
      - ./:/control-posts
    depends_on:
      mysql:
        condition: service_healthy
    env_file:
      - .env
    links:
      - mysql:mysql
    ports:
      - 8081:8081
      - 9229:9229

volumes:
  control-posts-node-modules:
  main:
